language: generic 
sudo: required # for superuser permissions
services: 
  - docker # docker needs to be preinstalled

# Steps needed before deploying or running tests
before_install:
  - docker build -t stephenwisner/docker-react -f Dockerfile.dev . # final dot is for build context; tag to get image b/c otherwise return id of image

script:
  - docker run -e CI=true stephenwisner/docker-react npm run test

deploy:
  provider: elasticbeanstalk # travis CI comes preconfigured with providers including elasticbeanstalk
  region: "us-east-1" # depends on where instance created
  app: "docker" # name of the app given
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-393263376523",
  bucket_path: "docker" # default equal to bucket name
  on:
    branch: master # limits deploy to master branch
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"